export const urls = [{
  url: "https://www.analyticsmania.com/post/tracking-errors-with-google-tag-manager/",
  title: "Tracking Errors with Google Tag Manager: 5 Things to Measure",
  seeded: false,
  loading: false,
},
{
  url: "https://www.analyticsmania.com/post/facebook-conversion-tracking-google-tag-manager/",
  title: "Facebook Conversion Tracking With Google Tag Manager",
  seeded: false,
  loading: false,
},
{
  url: "https://www.analyticsmania.com/post/duplicate-events-in-google-analytics-4-and-how-to-fix-them/",
  title: "Duplicate Events in Google Analytics 4 and How to Fix them",
  seeded: false,
  loading: false,
},
{
  url: "https://www.analyticsmania.com/post/google-analytics-4-events-not-showing-up-in-reports/",
  title: "Google Analytics 4 Events Not Showing Up in Reports?",
  seeded: false,
  loading: false,
},
{
  url: "https://www.analyticsmania.com/post/page-related-variables-and-triggers-in-google-tag-manager/",
  title: "Page Variables and Pageview Triggers in Google Tag Manager",
  seeded: false,
  loading: false,
},
{
  url: "https://www.analyticsmania.com/post/fire-once-per-page-vs-once-per-event-vs-unlimited-in-google-tag-manager/",
  title: "Fire Once per Page vs Once per Event vs Unlimited in Google Tag Manager",
  seeded: false,
  loading: false,
},
{
  url: "https://www.analyticsmania.com/post/track-linkedin-conversions-with-google-tag-manager/",
  title: "Track LinkedIn Conversions with Google Tag Manager",
  seeded: false,
  loading: false,
},
{
  url: "https://www.analyticsmania.com/post/scroll-tracking-with-google-analytics-4-and-google-tag-manager/",
  title: "Scroll tracking with Google Analytics 4 (GA4 Scroll Depth Tracking)",
  seeded: false,
  loading: false,
},
{
  url: "https://www.analyticsmania.com/post/thresholding-applied-in-google-analytics-4-do-this/",
  title: "Thresholding applied in Google Analytics 4? Do this",
  seeded: false,
  loading: false,
},
{
  url: "https://www.analyticsmania.com/post/not-set-in-google-analytics-4/",
  title: "Not set in Google Analytics 4. How to fix it?",
  seeded: false,
  loading: false,
}]